### ISSUE TITLE
Issues 10/13/2024

### ISSUE THREAD

**Issue by theeneon** [MathiasGruber/TheNinjaRPG#154]
- [x]  stealth is bugged in that when the condition ends, you're still stealthed until you use a move or heal action then you get your jutsus and stuff back

- [x] Prevent Buff is 100% it's not a percentage-based chance to trigger. 
- [x] Kage AI does not consume potions it uses. 
- [x] Allow Content Admin to unstuck players
- [x] After Kage is taken, the new Kage must wait 1 day to do Kage Stuff.
- [x] Clan Hall shouldn't be village upgrade. Villages can have as many clans as needed
- [x]  not showing users reports unless they are warnings/silences/bans
- [x] Timeout: The ability to mute someone from talking in global tavern for minimum 15mins to maximum 60 minutes
- [x] Swap Position of Global and Village Taverns so Village shows first
- [x] Block website from accessing TNRs public API 
- [x] Remove Med nin scaling on Healing jutsu and items. 
- [x] Apply  A Rank Mission selector, to A Rank Crimes, also apply the rank restrictions that are on missions to crimes
- [x] Unable to rearrange or delete custom rules on AIs
- [x] City of Mei should have PVP active right now its counted as a None PVP zone
- [x] Start Syndicate Issues
- [x] Restore 100 Reps to Korin(After you made the update, she then went and bought the slots thinking that she had to buy them to get them active)
<img width="237" alt="image" src="https://github.com/user-attachments/assets/580280ba-4f2c-42f8-8bc2-a5e00aad3019">

- [x] Basic Heal Cooldown should be 5
- [x] Answer Tickets

**Comment by nanubula** [comment]
There's nothing in the heal tag code that suggests it might use medical rank/xp. The only place medical rank is checked is in hospital, profile, and hard coded into basic heal effect.
I tested both static and % heal on both jutsu and item with all medical ranks, and it didn't have any effect

**Comment by d3t0ur** [comment]
Just a note in regards to the newer prevent tags. They're coded as Immunity rather than a resistance. RobPrevent, ClearPrevent, DebuffPrevent, BuffPrevent, CleansePrevent, SealPrevent are all coded as Immunity with a 100% effectiveness. We want them to be coded as a resistance so we can modify the chance of the effect triggering

**Comment by nanubula** [comment]
Is the Prevent with X percent supposed to be a chance to prevent per action, a chance to prevent per round, or a chance to prevent for X rounds? Right now it rolls at the set chance, then sets it to 100% chance after the first successful roll on any action, for the rest of the duration.
If it's one check per round, is there a nice way in tags.ts or process.ts to track status between actions in the same round like the tags, or would there have to be a new Ximmunity tag that gets added for a round?

**Comment by d3t0ur** [comment]
You can check the StunPrevent code for how it’s supposed to work. That one works as intended last time I checked. But if it doesn’t, ideally, we’d want it to check each round for the duration.

**Comment by nanubula** [comment]
Looks like StunPrevent checks once per action like the other prevents were setup to. I could submit a change to make the other prevent tags work the same if that's fine, but not sure how to make it last the whole round after checking once and making sure to not check again before the round is over. IMO though it makes sense for a % resist to try to resist every move individually instead of checking once in a round and having immunity that round the way I think you want it

SS showing multiple stuns with different resist results in same round
![image](https://github.com/user-attachments/assets/f707cb76-0d54-4102-bbd6-185971a64a5a)

**Comment by d3t0ur** [comment]
Once each round is fine. That’s intended. The main issue we’re having is that the other preventtags get defaulted to 100% no matter what Power we put in. So even if we put 1% power, they will have immunity.

**Comment by MathiasGruber** [comment]
Think I've solved all now, if not, create new issue :)
